name: Deploy to Azure Web App (Linux)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for azure/login OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      # 🔐 Azure login (OIDC). Make sure you created a Federated Credential
      # in Entra ID for this repo/branch and stored these secrets.
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD4AD34DD8FC43E1A79A922AB80D44EE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B24CE76A1E13453BB0DBFA20FFDD33E7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_180F0896FFEE4650974415557D08E2BB }}

      # 🚀 Deploy repo contents; App Service (Oryx) will run npm install & build on server
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kudospass'      # <— your Web App name
          slot-name: 'Production'
          package: .
